[versions]
junit = "5.10.0"
assertj = "3.26.3"

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
assertj-bom = { group = "org.assertj", name = "assertj-bom", version.ref = "assertj" }
