#
# Copyright (c) 2025. Eric McIntyre / Rivers of Orion
#

myProp=myValue
my.otherProp=Another value with an = in it
prop-name : This value has spaces
my-prefix.myProp=42
my.prefix.other-prop:nothing
my.prefix.other.prop = nothing else
name+with#funky?Characters!=Gimme the funk
My\ Prefix.%some$Other@PROP=Weird values
Another.Prefix..valid=3.1415
.how.about.this? : Seems to be okay
.=Is this valid?
It\ $eem$.property..names.are...Very\tFlexible=Value doesn't matter
\#Not.a.Comment=#Not a value
